package dk.au.measurementcollector.writers;
/**
 * Interface for writing samples to logs.
 * Writers can eg. be used to synchronize timestamps, write to
 * different files / databases etc.
 * 
 * @author Christian Melchior
 */
public interface LogWriter {
	
	/**
	 * Write a sample to the log.
	 * 
	 * @param tag		Keyword describing the sample
	 * @param sample	Sample data
	 * @param timestamp	Override timestamp generated by log writer
	 */
	public void writeSample(String tag, Object sample, long timeStamp);
	public void writeSample(String tag, Object sample);

	/**
	 * Create a new log file. Possible closing any current open ones in the
	 * process.
	 */
	public void createNewLog();	
	
	/**
	 * Close any currently open log files
	 */
	public void closeLog();
}
